//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMobileWebApp.Models
{
    using System;
	using Newtonsoft.Json;
	using ShopMobileWebApp.Services;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateOrder { get; set; }
    
        [JsonIgnore]
        public virtual User User
        {
            get
            {
                return DataManager.Users.FirstOrDefault(x=>x.Id==UserId);
            }
            set
            {
                UserId=value.Id;
            }
        }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
