//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMobileWebApp.Models
{
    using System;
	using Newtonsoft.Json;
	using ShopMobileWebApp.Services;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int OrderId { get; set; }
        public int CountProduct { get; set; }
        public string ColorProduct { get; set; }


        [JsonIgnore]
        public virtual Order Order
        {
            get
            {
                return DataManager.Orders.FirstOrDefault(x=>x.Id==OrderId);
            }
            set
            {
                OrderId=value.Id;
            }
        }
        [JsonIgnore]
        public virtual Product Product
        {
            get
            {
                return DataManager.Products.FirstOrDefault(x=>x.Id==ProductId);
            }
            set
            {
                ProductId=value.Id;
            }
        }
    }
}
