//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMobileWebApp.Models
{
    using System;
	using Newtonsoft.Json;
	using ShopMobileWebApp.Services;
    using System.Collections.Generic;
    
    public partial class PhotoProduct
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public int ProductId { get; set; }
        public string Format { get; set; }

        [JsonIgnore]
        public virtual Product Product
        {
            get
            {
                return DataManager.Products.FirstOrDefault(x=>x.Id==ProductId);
            }
            set
            {
                ProductId=value.Id;
            }
        }
    }
}
