//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMobileWebApp.Models
{
    using System;
	using Newtonsoft.Json;
	using ShopMobileWebApp.Services;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
            this.PhotoProduct = new HashSet<PhotoProduct>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1, int.MaxValue)]
        public int PriceRub { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [Required]
        public string Description { get; set; }

        [JsonIgnore]
        public virtual Category Category
        {
            get
            {
                return DataManager.Categorys.FirstOrDefault(x=>x.Id==CategoryId);
            }
            set
            {
                CategoryId=value.Id;
            }
        }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        [Range(1, 10)]
        public virtual ICollection<PhotoProduct> PhotoProduct { get; set; }
    }
}
