//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMobileWebApp.Models
{
    using System;
	using Newtonsoft.Json;
	using ShopMobileWebApp.Services;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Login { get; set; }
        [Required]
        public string Password { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        
        [JsonIgnore]
        public virtual Role Role
        {
            get
            {
                return DataManager.Roles.FirstOrDefault(x=>x.Id==RoleId);
            }
            set
            {
                RoleId=value.Id;
            }
        }
    }
}
