//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMobileApi.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class PhotoProduct
    {
        public int Id { get; set; }
        public byte[] Photo { get; set; }
        public int ProductId { get; set; }
    
        [JsonIgnore]
        public virtual Product Product { get; set; }
    }
}
